<?php
include '../src/Automobilis.php';
class Kupe extends Automobilis
{
protected $atidarytosDurys;
public function __construct($marke, $modelis, $atidarytosDurys) {
    parent::__construct($marke, $modelis);
if($atidarytosDurys){
    $this->$atidarytosDurys = 'TAIP';
}
if (!$atidarytosDurys) {
    $this->atidarytosDurys = 'NE';
}
return $this->atidarytosDurys;
}
public function informacija()
{
    $info = parent::informacija();
    $info .= ". Automobilio durys yra atidarytos:  " . $this->atidarytosDurys . '.';
//    return parent::informacija(); // TODO: Change the autogenerated stub
    return $info;
}

}
